// Terms & Disclaimers.
//
// NOT LEGAL ADVICE — this was drafted by an engineer, not an attorney, and should be
// reviewed by counsel before it is relied on. Placeholders marked [BRACKETS] must be
// filled in with the real legal entity, contact details and governing jurisdiction;
// a disclaimer naming the wrong entity protects nobody.
//
// Drafting principle: every statement here must be TRUE of what the site actually
// does. A disclaimer that misdescribes the product is itself a misrepresentation, so
// this separates the three kinds of content the audit produces — deterministic
// calculations, AI-written narrative, and third-party data — instead of calling it
// all "AI output".

import Link from "next/link";

export const metadata = {
  title: "Terms & Disclaimers",
  description: "Terms of use and disclaimers for the whole-home energy audit tool.",
};

const LAST_UPDATED = "August 4, 2026";
const COMPANY = "[LEGAL ENTITY NAME]";

const SECTIONS = [
  {
    h: "1. What this tool is",
    p: [
      `This website provides a preliminary, automated energy and backup-power assessment ("the Audit"). It is an informational and educational sales aid only.`,
      `The Audit is NOT a quote, proposal, bid, contract, binding offer, engineering study, load calculation, energy audit as defined by any standards body, or professional certification of any kind. No part of this site creates an obligation for ${COMPANY} to sell, install, or service any equipment at any price.`,
    ],
  },
  {
    h: "2. Estimates, not guarantees",
    p: [
      `Every figure produced by the Audit is an estimate derived from information you provide and from generalized assumptions. This includes, without limitation: generator sizing in kilowatts, coverage tier, recommended panel counts, energy offset percentages, utility bill projections, cost-of-outage figures, payback periods, and any stated or implied savings.`,
      `Actual results will differ, and may differ substantially. Equipment sizing depends on starting (surge) loads, panel configuration, existing electrical infrastructure, fuel type and supply, local code, and permitting — none of which this tool measures. Solar production varies with roof orientation, pitch, shading, weather, equipment age, and local conditions. Bill projections assume future utility rate changes that are inherently uncertain and may not occur.`,
      `No figure on this site is a guarantee, warranty, or promise of future performance, savings, cost, or outcome. Final specifications and pricing are determined only by an on-site assessment and a written agreement signed by both parties.`,
    ],
  },
  {
    h: "3. AI-generated content",
    p: [
      `Portions of the Audit — including the written analysis and narrative summary — are generated by an artificial intelligence language model. AI-generated content may contain errors, omissions, outdated information, or statements that are inaccurate or misleading despite our efforts to constrain it.`,
      `AI-generated content is not reviewed by a licensed professional before it is displayed to you. Do not rely on it as a statement of fact, and do not make a purchasing, financial, or safety decision based on it alone.`,
    ],
  },
  {
    h: "4. Third-party and public data",
    p: [
      `The Audit may display information retrieved from third-party and government sources, including the U.S. Energy Information Administration (EIA), the National Renewable Energy Laboratory (NREL) Utility Rate Database, and public postal-code geocoding services.`,
      `That data is provided by those sources "as is." It may be incomplete, aggregated to a state or utility level rather than specific to your address, published on a lag of a year or more, superseded, or simply wrong. ${COMPANY} does not control, verify, endorse, or warrant third-party data and is not responsible for it. Where a figure reflects a state or regional average, it is labeled as such and should not be read as a measurement of your home, street, or ZIP code.`,
      `Outage frequency and duration shown in the Audit reflect what you reported to us during intake. They are your own recollection, not a measured or verified record of service interruptions at your address.`,
    ],
  },
  {
    h: "5. No professional advice",
    p: [
      `Nothing on this site constitutes engineering, electrical, construction, safety, insurance, financial, investment, tax, or legal advice. Generator sizing and installation, electrical work, and fuel connections must be performed by appropriately licensed professionals in accordance with applicable codes and permits.`,
      `Consult a qualified professional before acting on anything you read here. Never rely on this tool for decisions involving life-safety equipment, including medical devices dependent on electrical power.`,
    ],
  },
  {
    h: "6. Your information",
    p: [
      `The Audit is only as accurate as the information entered into it. Figures are computed from your responses and are not independently verified. Inaccurate, incomplete, or estimated inputs will produce inaccurate outputs.`,
    ],
  },
  {
    h: "7. No warranty",
    p: [
      `This site and the Audit are provided "as is" and "as available," without warranties of any kind, whether express, implied, or statutory, including without limitation any implied warranties of merchantability, fitness for a particular purpose, accuracy, completeness, title, or non-infringement.`,
      `${COMPANY} does not warrant that the site will be uninterrupted, error-free, secure, or that any defect will be corrected.`,
    ],
  },
  {
    h: "8. Limitation of liability",
    p: [
      `To the fullest extent permitted by applicable law, ${COMPANY} and its officers, employees, contractors, and affiliates shall not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, or for any loss of profits, revenue, data, savings, business, or goodwill, arising out of or relating to your use of or reliance on this site or the Audit — whether based in contract, tort, negligence, strict liability, or any other theory, and whether or not we were advised of the possibility of such damages.`,
      `Some jurisdictions do not allow the exclusion or limitation of certain warranties or liabilities, so some of the above may not apply to you. Nothing in these terms limits liability that cannot lawfully be limited, including liability for fraud or fraudulent misrepresentation.`,
    ],
  },
  {
    h: "9. Changes",
    p: [
      `The Audit's methodology, assumptions, data sources, and these terms may change at any time without notice. A figure shown to you on one date may differ from a figure shown for the same home on another date. These terms apply as posted at the time of your use.`,
    ],
  },
  {
    h: "10. Governing law",
    p: [
      `These terms are governed by the laws of [STATE / JURISDICTION], without regard to conflict-of-law principles.`,
    ],
  },
  {
    h: "11. Contact",
    p: [
      `Questions about these terms, or about any figure the Audit produced for your home, can be directed to ${COMPANY} at [CONTACT EMAIL] or [PHONE].`,
    ],
  },
];

export default function TermsPage() {
  return (
    <main className="legal-main">
      <header className="legal-header">
        <h1>Terms &amp; Disclaimers</h1>
        <p className="legal-updated">Last updated: {LAST_UPDATED}</p>
        <div className="legal-lede">
          <p>
            <strong>
              Read this before relying on anything in your energy audit.
            </strong>{" "}
            The audit is a preliminary estimate produced by automated calculations, AI-generated
            written analysis, and third-party data. It is not a quote, not a contract, not
            professional advice, and not a guarantee of any cost, saving, or outcome. Figures may be
            inaccurate or out of date. Final equipment, pricing, and performance are determined only
            by an on-site assessment and a signed written agreement.
          </p>
        </div>
      </header>

      {SECTIONS.map((s) => (
        <section className="legal-section" key={s.h}>
          <h2>{s.h}</h2>
          {s.p.map((para, i) => (
            <p key={i}>{para}</p>
          ))}
        </section>
      ))}

      <p className="legal-back">
        <Link href="/">← Back to home</Link>
      </p>
    </main>
  );
}
